# Generated by Django 3.2.5 on 2021-07-15 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('color', models.CharField(default='pink', max_length=50)),
                ('event_from', models.DateTimeField()),
                ('event_to', models.DateTimeField()),
                ('event_title', models.CharField(max_length=50)),
                ('event_desc', models.TextField(default=None)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
