# Generated by Django 3.2.5 on 2021-07-13 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('route_desc', models.CharField(default=None, max_length=50)),
                ('grade', models.IntegerField(default=1)),
                ('attempts', models.IntegerField(default=0)),
                ('timing', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_attempted', models.DateField(auto_now_add=True)),
                ('climb_type', models.CharField(choices=[('TR', 'Toprope'), ('LD', 'Lead'), ('BD', 'Boulder'), ('SP', 'Speed')], default='BD', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('tracker_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default=None)),
                ('route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.route')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
