# Generated by Django 3.2.5 on 2021-07-10 16:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tracker_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=10)),
                ('attempts', models.IntegerField(default=0)),
                ('date_attempted', models.DateField(auto_now_add=True)),
                ('timing', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='tracker',
            name='id',
        ),
        migrations.AddField(
            model_name='tracker',
            name='tracker_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
