# Generated by Django 3.2.5 on 2021-07-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_auto_20210710_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='climb_type',
            field=models.CharField(choices=[('TR', 'Toprope'), ('L', 'Lead'), ('B', 'Boulder'), ('S', 'Speed')], default='TR', max_length=2),
        ),
    ]
