# Generated by Django 3.2.5 on 2021-07-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_tracker_climb_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_desc',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
