# Generated by Django 3.2.5 on 2021-07-11 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_route_route_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes_Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.route')),
                ('tracker_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tracker.tracker')),
            ],
        ),
    ]
