# Generated by Django 3.2.5 on 2021-07-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_routes_tracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes_tracker',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
