# Generated by Django 3.2.5 on 2021-07-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
